import { NextResponse } from "next/server";
import {
  ADMIN_TICK_PRESETS,
  JOIN_PATH,
  JOINER_FIELD_BY_PRESET,
} from "@/lib/showcase/contract";
import { currentUser } from "@/lib/showcase/current-user";
import { getAccount } from "@/lib/showcase/accounts";
import { createJoiner, stepsFromBlocks } from "@/lib/showcase/joiners";
import { createJoinerToken } from "@/lib/showcase/joiner-session";
import { rateLimit } from "@/lib/showcase/rate-limit";
import { findTemplate, SENDER } from "@/lib/email";
import { renderEmail } from "@/lib/email/html";
import { sendEmail } from "@/lib/email/send";

/**
 * Giving somebody a seat, which is the first thing in this product that
 * actually reaches a stranger.
 *
 * Everything else that sends is addressed to the person who pressed the button.
 * This one is addressed to whoever they typed, so it is the first route here
 * with the shape of an open relay — and the mitigations are the whole design of
 * the file rather than a check at the top of it:
 *
 * 1. **The words are ours.** The caller picks no template and writes no prose.
 *    One template, chosen here by name, and the only things they supply are the
 *    values that make it about a particular person — a name, a role, a date. So
 *    the worst message a determined caller can compose is a genuine invitation
 *    to a company they don't work for, which is spam nobody would pay for.
 * 2. **One recipient.** One address, checked against a shape that admits no
 *    separator and no newline, so this cannot be turned into a list.
 * 3. **Every merged value is flattened to one line and cut short.** A newline in
 *    a name is how a merge field becomes a mail header, and eighty characters is
 *    more than a job title needs and less than a message.
 * 4. **Signed in, and limited.** The session is what stands between a stranger
 *    and somebody else's provider key; the limiter is what stands between a
 *    signed-in caller and the same key, because a cookie doesn't stop a loop.
 *
 * What remains after all four is a signed-in user mailing a small number of
 * addresses of their choosing a fixed, honest invitation. That is the product,
 * and it is also the residual risk — which is why the copy is fixed and the
 * volume is capped rather than the address being trusted.
 *
 * Since the new starter got a screen of their own, this route also mints the
 * credential that reaches it. That raises the stakes on all four points above:
 * the thing being posted to a stranger is no longer only prose, it is a signed
 * token that signs the holder in as them. So the link is built here from a
 * joiner this route created, never from anything the caller sent, and it goes in
 * exactly one place — the button — because every additional copy of a bearer
 * credential is another place it can be forwarded from.
 */

/** The trigger email. Not the caller's choice — see above. */
const TEMPLATE_ID = "seat-invite";

/** Spends nothing from OpenAI's budget, and mustn't pretend otherwise — see
    the note on `spend` in rate-limit.ts. An invite that drained the chat's daily
    cap would let this button switch Craig off for the day. */
const LIMIT_OPTIONS = { spend: false } as const;

/**
 * Who gets a silent copy of every invitation.
 *
 * So the person whose product this is can read what a stranger actually
 * received, rather than trusting a green tick. The default is in code rather
 * than only in `.env.example`, because a copy that silently stops arriving when
 * an environment is missing a variable is worse than no copy at all.
 *
 * Now that the invitation carries a working link it also carries a working
 * credential, so whoever reads this mailbox can open any new starter's
 * onboarding as them. That is tolerable for one address belonging to the person
 * who runs the deployment and would not be tolerable for a shared inbox or a
 * team alias, which is the reason it stays a single address.
 */
const BCC =
  process.env.SHOWCASE_INVITE_BCC?.trim() || "dzakyayrosihan@gmail.com";

/** Longer than any real name or job title, shorter than a message. */
const MAX_FIELD = 80;

/** RFC 5321's ceiling on an address. Anything longer is not a mistake. */
const MAX_ADDRESS = 254;

/**
 * Identifiers — a workflow's, a block's, a preset's — are generated by us and
 * are never read by anybody, so they only need to be long enough not to
 * truncate a real one and short enough not to be a payload.
 */
const MAX_ID = 64;

/**
 * The most steps one invitation may carry.
 *
 * The blocks arrive in the request body because the workflow lives in the
 * browser, which means the array's length is a stranger's choice and the
 * snapshot it becomes is written to disk. Forty is several times the longest
 * onboarding anybody has built here and small enough that a hostile body can't
 * turn one invitation into a large write. Extra entries are dropped rather than
 * refused: a workflow that grew past this is still a workflow somebody should
 * be able to invite into, and the first forty steps are the ones that matter.
 */
const MAX_BLOCKS = 40;

const noStore = { "Cache-Control": "no-store" };

/**
 * A caller-supplied value, as one harmless line.
 *
 * Control characters first, whitespace second. A newline is caught by either,
 * but the unprintable ones either side of it — NUL, and the C0 range generally
 * — are only caught by the first, and those are the characters that survive a
 * naive trim and end up in a header.
 */
function oneLine(value: unknown, max = MAX_FIELD): string {
  if (typeof value !== "string") return "";
  return value
    .replace(/[\u0000-\u001f\u007f]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, max);
}

/**
 * One address, or nothing.
 *
 * Deliberately two tests rather than one long expression. The shape check is
 * the usual "something, an @, something with a dot" — permissive, because
 * addresses are stranger than people think and refusing a real one is a bug the
 * person can't work around. The forbidden set is the part that matters: comma
 * and semicolon are how one field becomes several recipients, angle brackets
 * and quotes are how it becomes a display name wrapping somebody else's
 * address, and whitespace covers every newline that turns a value into a
 * header. An apostrophe is allowed through, because o'brien@ is a person.
 */
function oneAddress(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const address = value.trim();

  if (address.length === 0 || address.length > MAX_ADDRESS) return null;
  if (/[\s,;<>"\\\u0000-\u001f\u007f]/.test(address)) return null;
  if (!/^[^@]+@[^@]+\.[^@]{2,}$/.test(address)) return null;

  return address;
}

/**
 * `2026-08-24` as "Monday 24 August".
 *
 * Built from the parts rather than passed to `new Date(string)`, which reads a
 * bare date as UTC midnight and then formats it in the server's timezone —
 * anywhere west of Greenwich, that is yesterday. A start date that is one day
 * out in the invitation is the kind of error nobody notices until somebody
 * turns up on the wrong morning.
 */
function readableDate(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const parts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value.trim());
  if (!parts) return null;

  const date = new Date(
    Number(parts[1]),
    Number(parts[2]) - 1,
    Number(parts[3]),
  );
  if (Number.isNaN(date.getTime())) return null;

  return new Intl.DateTimeFormat("en-AU", {
    weekday: "long",
    day: "numeric",
    month: "long",
  }).format(date);
}

/**
 * The workflow's blocks, as much of each one as a person's onboarding needs.
 *
 * They have to come up on the request. The workflow itself lives in the
 * browser's store — there is no server-side copy to read one out of — so the
 * only way this route can know what the new starter will be asked for is to be
 * told, and being told by a client means being told by whoever is holding the
 * client. Hence the same treatment every other field gets, one layer down.
 *
 * Malformed entries are skipped rather than refused. The array is a snapshot of
 * a canvas somebody has been dragging things around on, and one block that
 * arrives without a title should cost that block rather than the invitation —
 * the person is still starting on Monday. What it must not do is arrive
 * *silently* empty, which is why the caller checks the result rather than this.
 *
 * Two things are load-bearing beyond the trimming:
 *
 * Ids are de-duplicated, because a step is answered by id. Two steps sharing one
 * would make the second unreachable forever — `completeStep` finds the first and
 * stops — and it would look like a screen that ignores you rather than like bad
 * data.
 *
 * A preset survives if it names a step somebody can actually complete — either
 * one the new starter answers (`JOINER_FIELD_BY_PRESET`) or one the admin ticks
 * off (`ADMIN_TICK_PRESETS`). Both, and it has to be both: keeping only the
 * first meant every admin step arrived with its preset stripped, so
 * `stepsFromBlocks` gave it no `actor`, and work the company had to do showed
 * up on the new starter's screen as "nobody's waiting on you" and never
 * appeared as a tick on the admin's. The step existed and neither side owned
 * it.
 *
 * `Object.hasOwn` on the map rather than `in`, because it is a plain object
 * literal: a preset of `constructor` or `toString` would look up to something
 * inherited from `Object.prototype` and put a function where a `JoinerField`
 * belongs — a step claiming a form nobody can render. The set needs no such
 * care, which is half the reason it is a `Set`.
 *
 * Presets that are neither are dropped to `undefined` rather than the block
 * being dropped: those steps are real work that simply isn't anybody's here,
 * `stepsFromBlocks` keeps them for exactly that reason, and it never reads a
 * preset for anything else.
 */
function blocksFrom(value: unknown) {
  if (!Array.isArray(value)) return [];

  const seen = new Set<string>();
  const blocks: { id: string; title: string; kind: string; preset?: string }[] =
    [];

  for (const entry of value.slice(0, MAX_BLOCKS)) {
    if (!entry || typeof entry !== "object") continue;
    const raw = entry as Record<string, unknown>;

    const id = oneLine(raw.id, MAX_ID);
    const title = oneLine(raw.title);
    if (!id || !title || seen.has(id)) continue;
    seen.add(id);

    const preset = oneLine(raw.preset, MAX_ID);
    blocks.push({
      id,
      title,
      kind: oneLine(raw.kind, MAX_ID),
      preset:
        Object.hasOwn(JOINER_FIELD_BY_PRESET, preset) ||
        ADMIN_TICK_PRESETS.has(preset)
          ? preset
          : undefined,
    });
  }

  return blocks;
}

/**
 * Where the link in the email should point.
 *
 * Derived from the request, so the same code works on localhost, on a preview
 * deployment and in production without anybody remembering to set a variable —
 * and a link that points at the wrong host is a link that cannot be recovered
 * from, because it has already been sent.
 *
 * The override exists because the request's own host is, in the general case,
 * attacker-controlled: a `Host` header is just a header, and behind a proxy that
 * forwards one without checking it, this route would happily mail a stranger a
 * valid onboarding token pointed at somebody else's server. Next resolves
 * `request.url` from the forwarded host when it trusts the proxy in front of it,
 * which covers the deployments this actually runs on; `SHOWCASE_ORIGIN` is the
 * answer for one it doesn't, and setting it removes the header from the decision
 * entirely.
 */
function originOf(request: Request): string {
  const configured = process.env.SHOWCASE_ORIGIN?.trim().replace(/\/+$/, "");
  if (configured) return configured;
  return new URL(request.url).origin;
}

const refuse = (error: string, status: number) =>
  NextResponse.json({ ok: false, error }, { status, headers: noStore });

export async function POST(request: Request) {
  const session = await currentUser();
  if (!session) return refuse("Not signed in.", 401);

  const limit = rateLimit(`showcase-invite:${session.email}`, LIMIT_OPTIONS);
  if (!limit.ok) {
    return NextResponse.json(
      { ok: false, error: limit.message ?? "Too many invitations at once." },
      {
        status: 429,
        headers: limit.retryAfter
          ? { ...noStore, "Retry-After": String(limit.retryAfter) }
          : noStore,
      },
    );
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return refuse("Expected JSON.", 400);
  }

  const input = (body ?? {}) as Record<string, unknown>;

  const name = oneLine(input.name);
  if (!name) return refuse("Enter their name.", 400);

  const to = oneAddress(input.email);
  if (!to) return refuse("That doesn't look like an email address.", 400);

  /* Both spellings of the same day are kept. The email wants "Monday 24
     August", and the record kept for the new starter wants the `YYYY-MM-DD` it
     came as — a stored date that has already been through a formatter is a date
     nothing downstream can compare, sort or re-render in anybody else's
     locale. */
  const startISO = oneLine(input.startDate, 10);
  const startDate = readableDate(startISO);
  if (!startDate) return refuse("Pick the day they start.", 400);

  const role = oneLine(input.role);
  const workflowId = oneLine(input.workflowId, MAX_ID);
  const workflowName = oneLine(input.workflowName) || "Onboarding";

  /* What this person will actually be asked for, frozen now. `stepsFromBlocks`
     drops the trigger and keeps everything else, so an empty result means the
     workflow had nothing in it but its trigger — or that the blocks never
     arrived at all.

     Refused rather than allowed through, and the refusal is the point. Sending
     somebody a warm email promising "a few things we need from you" and landing
     them on an empty checklist is the failure this would otherwise produce
     silently, on the day somebody changes how the client posts this rather than
     on the day anybody edits this file. */
  const steps = stepsFromBlocks(blocksFrom(input.blocks));
  if (steps.length === 0) {
    return refuse(
      "There's nothing in that workflow for them to do yet. Add a step, then invite them.",
      400,
    );
  }

  /* The company is read from the account, never from the request. It is the
     name the invitation is signed with, and a value the caller could set would
     let this route send a convincing welcome to a company they have nothing to
     do with — the one merge field where being wrong is a lie rather than a
     typo. */
  const account = getAccount(session.email);
  if (!account) return refuse("Not signed in.", 401);
  if (!account.company) {
    return refuse(
      "Your account has no company name on it, and the invitation goes out under it.",
      400,
    );
  }

  const template = findTemplate(TEMPLATE_ID);
  if (!template) {
    return refuse("The invitation template is missing.", 500);
  }

  /* The person exists before the email does, and it has to be that way round:
     the link is derived from their id, so there is nothing to put in the message
     until the record is written. The cost is an honest one — a send that fails
     after this leaves a joiner nobody was told about.

     That is the better of the two failures. The alternative is an email
     carrying a link to a person who doesn't exist, which fails in the new
     starter's hands a week later with nothing anybody can do about it; this one
     fails in the admin's hands immediately, says so, and is fixed by inviting
     them again. The client only writes the person into People on success, so a
     failed send doesn't put a row in front of anybody either. */
  const joiner = createJoiner({
    email: to,
    name,
    role,
    startDate: startISO,
    /* Whose list they appear on. From the session, never the request — this is
       the field that decides which account can read their progress. */
    accountEmail: account.email,
    company: account.company,
    workflowId,
    workflowName,
    steps,
  });

  /* The credential, and the only one they will ever have. Built after the
     record so it can name it, and never derived from anything in the request —
     an address, a name and a start date are all things somebody else could
     know, and a link guessable from them would be a link anybody who knows a
     new starter's details could walk in through. */
  const token = await createJoinerToken(joiner.id);
  const link = `${originOf(request)}${JOIN_PATH}?token=${encodeURIComponent(token)}`;

  /* Every token in the vocabulary, not merely the ones this template reads
     today. `render` fills anything absent from the *preview's* fixtures — so a
     token left out here doesn't arrive blank, it arrives as a stranger's name
     in somebody's real welcome email, and it does that the day the copy gains a
     merge field rather than the day anyone changes this file.

     Which is why the two with nothing real behind them at invite time are
     supplied empty. An invitation with a visible gap in it is a bug somebody
     reports; an invitation naming a person from a demo company reads as
     correct.

     `step` and `owner` are those two: an invitation is about the whole
     onboarding rather than about any one step of it, and nobody owns it but the
     person receiving it. The invitation copy is written not to use either, and
     supplying them empty is what makes that a choice rather than a dependency —
     a template that starts using one gets a blank, which is visible, instead of
     Jason's name, which isn't. */
  const values = {
    first_name: name.split(" ")[0],
    full_name: name,
    company: account.company,
    role,
    start_date: startDate,
    sender: session.name,
    workflow: workflowName,
    step: "",
    owner: "",
    link,
  };

  const { subject, html, text } = renderEmail(template, values);
  const fromName = SENDER.name(account.company);

  const result = await sendEmail({
    to,
    bcc: BCC,
    subject,
    html,
    text,
    fromName,
  });

  if (!result.ok) {
    /* Configuration this deployment got wrong is a 500 — the caller did nothing
       unusual and can't fix it by asking differently. A provider that refused
       or vanished is a 502. Neither ever carries Resend's own words. */
    const status =
      result.reason === "rate-limited"
        ? 429
        : result.reason === "unreachable" || result.reason === "rejected"
          ? 502
          : 500;

    return NextResponse.json(
      { ok: false, reason: result.reason, error: result.message },
      {
        status,
        headers: result.retryAfter
          ? { ...noStore, "Retry-After": String(result.retryAfter) }
          : noStore,
      },
    );
  }

  /* Enough for the caller to say what happened without guessing at it, and the
     id is the part that makes "it sent" checkable against the Resend dashboard
     rather than a claim this route makes about itself. The bcc is echoed for
     the same reason: it goes to whoever runs this deployment, and it is the one
     recipient the response is the only evidence of.

     `joinerId` is separate from `id` and deliberately not named `id` itself.
     They are two identifiers for two different things — one message and one
     person — and the client already reads `id` as the message's. Overloading it
     would silently repoint every existing reader at the wrong entity, which is
     the class of change that type-checks, runs, and is wrong.

     The token is not here and must not be. The client's job is to remember
     which person it just created so it can ask after their progress; it has no
     use for the credential, and a bearer token that has been through a browser
     is a bearer token in a devtools network tab and a support screenshot. */
  return NextResponse.json(
    {
      ok: true,
      id: result.id,
      joinerId: joiner.id,
      to,
      bcc: BCC,
      from: `${fromName} <${SENDER.address}>`,
      subject,
      person: { name, role, startDate },
      workflow: { id: workflowId, name: workflowName },
    },
    { headers: noStore },
  );
}
