/**
 * Generated by the Supabase MCP (`generate_typescript_types`) against project
 * yoajqnuyeglasriygtdc on 9 August 2026 — do not edit by hand. Re-generate
 * after every migration; the columns here are the contract the stores compile
 * against, and a drifted copy fails at runtime instead of in `tsc`.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      accounts: {
        Row: {
          company: string
          created_at: string
          email: string
          id: string
          name: string
          owner_id: string
        }
        Insert: {
          company: string
          created_at?: string
          email: string
          id?: string
          name: string
          owner_id: string
        }
        Update: {
          company?: string
          created_at?: string
          email?: string
          id?: string
          name?: string
          owner_id?: string
        }
        Relationships: []
      }
      connections: {
        Row: {
          account_id: string
          admin_email: string | null
          connected_at: string
          domain: string | null
          id: string
          needs_reconnect: boolean
          provider: string
          scopes: string[]
          token_ciphertext: string
          token_iv: string
          token_tag: string
        }
        Insert: {
          account_id: string
          admin_email?: string | null
          connected_at?: string
          domain?: string | null
          id?: string
          needs_reconnect?: boolean
          provider: string
          scopes?: string[]
          token_ciphertext: string
          token_iv: string
          token_tag: string
        }
        Update: {
          account_id?: string
          admin_email?: string | null
          connected_at?: string
          domain?: string | null
          id?: string
          needs_reconnect?: boolean
          provider?: string
          scopes?: string[]
          token_ciphertext?: string
          token_iv?: string
          token_tag?: string
        }
        Relationships: [
          {
            foreignKeyName: "connections_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      joiners: {
        Row: {
          account_email: string
          account_id: string
          company: string
          email: string
          id: string
          invited_at: string
          name: string
          role: string
          start_date: string
          steps: Json
          workflow_id: string
          workflow_name: string
        }
        Insert: {
          account_email: string
          account_id: string
          company: string
          email: string
          id?: string
          invited_at?: string
          name: string
          role?: string
          start_date: string
          steps: Json
          workflow_id: string
          workflow_name: string
        }
        Update: {
          account_email?: string
          account_id?: string
          company?: string
          email?: string
          id?: string
          invited_at?: string
          name?: string
          role?: string
          start_date?: string
          steps?: Json
          workflow_id?: string
          workflow_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "joiners_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          account_id: string
          cancel_at_period_end: boolean
          current_period_end: number
          customer_id: string
          price_id: string
          seats: number
          status: string
          subscription_id: string
          updated_at: string
        }
        Insert: {
          account_id: string
          cancel_at_period_end?: boolean
          current_period_end?: number
          customer_id: string
          price_id?: string
          seats?: number
          status: string
          subscription_id: string
          updated_at?: string
        }
        Update: {
          account_id?: string
          cancel_at_period_end?: boolean
          current_period_end?: number
          customer_id?: string
          price_id?: string
          seats?: number
          status?: string
          subscription_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: true
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      workflows: {
        Row: {
          account_id: string
          blocks: Json
          created_at: string
          drafted_by: string | null
          id: string
          name: string
          published: boolean
          revealed_at: string | null
          updated_at: string
        }
        Insert: {
          account_id: string
          blocks?: Json
          created_at?: string
          drafted_by?: string | null
          id: string
          name: string
          published?: boolean
          revealed_at?: string | null
          updated_at?: string
        }
        Update: {
          account_id?: string
          blocks?: Json
          created_at?: string
          drafted_by?: string | null
          id?: string
          name?: string
          published?: boolean
          revealed_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workflows_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      replace_joiner_steps: {
        Args: { p_expected: Json; p_id: string; p_next: Json }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never
