#!/usr/bin/env python3
"""Vendor a fixed set of Material Symbols (Rounded) into a single TSX module.

Run again after editing ICONS to add or drop an icon:
    python3 scripts/gen-icons.py
"""
import re
import sys
import urllib.request

BASE = ("https://raw.githubusercontent.com/google/material-design-icons/master"
        "/symbols/web/{n}/materialsymbolsrounded/{n}_24px.svg")

# export name -> Material Symbols name
ICONS = {
    "Add": "add",
    "ArrowBack": "arrow_back",
    "CalendarToday": "calendar_today",
    "ChevronLeft": "chevron_left",
    "LeftPanelClose": "left_panel_close",
    "LeftPanelOpen": "left_panel_open",
    "Lock": "lock",
    "Logout": "logout",
    "Mail": "mail",
    "MoreHoriz": "more_horiz",
    "Person": "person",
    "RightPanelClose": "right_panel_close",
    "RightPanelOpen": "right_panel_open",
    "Settings": "settings",
    "Visibility": "visibility",
    "VisibilityOff": "visibility_off",
    "GraphicEq": "graphic_eq",
    "Mic": "mic",
    "ArrowUpward": "arrow_upward",
    "AttachFile": "attach_file",
    "AutoAwesome": "auto_awesome",
    "Close": "close",
    "ContentCopy": "content_copy",
    "ExpandLess": "expand_less",
    "ExpandMore": "expand_more",
    "Forum": "forum",
    "Refresh": "refresh",
    "StopCircle": "stop_circle",
    "Tune": "tune",
    "ArrowForward": "arrow_forward",
    "CalendarMonth": "calendar_month",
    "Check": "check",
    "ChevronRight": "chevron_right",
    "DarkMode": "dark_mode",
    "Delete": "delete",
    "Description": "description",
    "DragIndicator": "drag_indicator",
    "Info": "info",
    "LaptopMac": "laptop_mac",
    "LightMode": "light_mode",
    "PersonAdd": "person_add",
    "ProgressActivity": "progress_activity",
    "Search": "search",
    "Warning": "warning",
}

HEADER = '''import * as React from "react";
import { cn } from "@/lib/cn";

/**
 * Material Symbols (Rounded), vendored as inline SVG.
 *
 * Generated by scripts/gen-icons.py — edit the ICONS map there and re-run
 * rather than hand-editing this file.
 *
 * Vendored rather than pulled from a package because we use ~15 icons and the
 * npm sets ship thousands of files; this keeps install size flat and means no
 * runtime dependency. Material Symbols are Apache-2.0.
 *
 * Each icon carries its own viewBox. Most Material Symbols use the
 * 0 -960 960 960 space, but a few files in that directory are still in the
 * legacy 0 0 24 24 space and ship no viewBox attribute at all — assuming one
 * space for all of them renders those as an invisible speck. The generator
 * reads it per file.
 *
 * Paths fill with currentColor so they inherit text colour, and size comes
 * from a className (`size-4`), which overrides the width/height attributes.
 */

export type IconProps = React.SVGProps<SVGSVGElement>;

function icon(displayName: string, viewBox: string, d: string) {
  const Component = React.forwardRef<SVGSVGElement, IconProps>(
    function Icon({ className, ...props }, ref) {
      return (
        <svg
          ref={ref}
          xmlns="http://www.w3.org/2000/svg"
          viewBox={viewBox}
          width="24"
          height="24"
          fill="currentColor"
          aria-hidden="true"
          focusable="false"
          className={cn("shrink-0", className)}
          {...props}
        >
          <path d={d} />
        </svg>
      );
    },
  );
  Component.displayName = displayName;
  return Component;
}
'''


def fetch(name: str) -> tuple[str, str]:
    """Returns (viewBox, path data) for one icon."""
    url = BASE.format(n=name)
    with urllib.request.urlopen(url, timeout=30) as r:
        svg = r.read().decode()

    vb = re.search(r'viewBox="([^"]+)"', svg)
    if vb:
        view_box = vb.group(1)
    else:
        # No viewBox: legacy 24px file. Build one from width/height so the
        # coordinates land in the right space.
        w = re.search(r'width="(\d+)"', svg)
        h = re.search(r'height="(\d+)"', svg)
        view_box = f"0 0 {w.group(1) if w else 24} {h.group(1) if h else 24}"

    paths = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
    if not paths:
        raise SystemExit(f"no path found in {url}")
    if len(paths) > 1:
        print(f"  ! {name}: {len(paths)} paths, merging", file=sys.stderr)
    return view_box, " ".join(paths)


def main():
    out = [HEADER]
    spaces = {}
    for export, mat in ICONS.items():
        view_box, d = fetch(mat)
        spaces.setdefault(view_box, []).append(export)
        print(f"  {export:18} <- {mat:20} [{view_box}]")
        out.append(
            f'\nexport const {export} = icon(\n  "{export}",\n'
            f'  "{view_box}",\n  "{d}",\n);'
        )
    if len(spaces) > 1:
        print("\n  note: mixed coordinate spaces —")
        for vb, names in spaces.items():
            print(f"    {vb}: {', '.join(names)}")
    target = "src/components/ui/icons.tsx"
    with open(target, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"\nwrote {target} ({len(ICONS)} icons)")


if __name__ == "__main__":
    main()
