"""
Vendors brand marks for the integration blocks.

Run again after editing BRANDS to add or drop one:
    python3 scripts/gen-brand-icons.py

Source is Simple Icons (https://simple-icons.org), CC0-1.0. The *icons* are
public domain; the trademarks they depict are not, and are used here only to
identify the service each block provisions, which is what nominative use is
for.

Material Symbols has no brand logos at all — all 4,389 of them are generic —
so this is a second, separate set rather than an addition to gen-icons.py.

Not available anywhere freely licensed: Slack, AWS, Microsoft. Simple Icons
carried all three and removed them at the trademark holders' request, so
there's no legitimate copy to vendor. Those blocks fall back to a Material
glyph, which is a deliberate gap rather than an oversight.
"""
import re
import sys
import urllib.request

SRC = ("https://raw.githubusercontent.com/simple-icons/simple-icons"
       "/develop/icons/{slug}.svg")

# export name -> simple-icons slug
BRANDS = {
    "Google": "google",
    "GitHub": "github",
    "Linear": "linear",
    "Notion": "notion",
    "Figma": "figma",
    "Jira": "jira",
    "Zoom": "zoom",
    "OnePassword": "1password",
    "Okta": "okta",
    "Asana": "asana",
    "Dropbox": "dropbox",
    "Greenhouse": "greenhouse",
    "Gusto": "gusto",
    "HubSpot": "hubspot",
    "Stripe": "stripe",
}

HEADER = '''import * as React from "react";
import { cn } from "@/lib/cn";
import type { IconProps } from "./icons";

/**
 * Brand marks for the services a workflow provisions.
 *
 * Generated by scripts/gen-brand-icons.py — edit the BRANDS map there and
 * re-run rather than hand-editing this file.
 *
 * Separate from icons.tsx because these are a different kind of thing. Material
 * Symbols ships no brand logos — not one, across the whole set — so these come
 * from Simple Icons (CC0-1.0). They're single-path silhouettes on a 24x24 grid,
 * which sits close enough to Material's filled style that a row mixing the two
 * reads as one set.
 *
 * Slack, AWS and Microsoft are missing on purpose. Simple Icons carried them
 * and removed them when the trademark holders asked, so there is no freely
 * licensed copy to vendor. Those blocks use a Material glyph instead. If Katalis
 * has permission to use those marks, drop the SVG in here by hand.
 *
 * Rendered in currentColor, not brand colour: these sit inside a tinted tile
 * next to Material icons, and fifteen different brand colours in one dialog is
 * a fruit salad.
 */

export type BrandIconProps = IconProps;

function brand(displayName: string, d: string) {
  const Component = React.forwardRef<SVGSVGElement, BrandIconProps>(
    function BrandIcon({ className, ...props }, ref) {
      return (
        <svg
          ref={ref}
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          width="24"
          height="24"
          fill="currentColor"
          aria-hidden="true"
          focusable="false"
          className={cn("shrink-0", className)}
          {...props}
        >
          <path d={d} />
        </svg>
      );
    },
  );
  Component.displayName = displayName;
  return Component;
}
'''


def fetch(slug: str) -> str:
    url = SRC.format(slug=slug)
    with urllib.request.urlopen(url) as r:
        svg = r.read().decode("utf-8")
    m = re.search(r'\sd="([^"]+)"', svg)
    if not m:
        raise SystemExit(f"no path in {url}")
    return m.group(1)


def main() -> None:
    target = "src/components/ui/brand-icons.tsx"
    parts = [HEADER]

    for export, slug in BRANDS.items():
        d = fetch(slug)
        parts.append(
            f'\nexport const {export} = brand("{export}", "{d}");\n'
        )
        print(f"  {export:<14} <- {slug}")

    with open(target, "w") as f:
        f.write("".join(parts))

    print(f"\nwrote {target} ({len(BRANDS)} brands)")
    print("not available freely licensed: Slack, AWS, Microsoft")


if __name__ == "__main__":
    sys.exit(main())
