#!/usr/bin/env python3
"""Vendor a fixed set of Material Symbols (Rounded) into a single TSX module.

Run again after editing ICONS to add or drop an icon:
    python3 scripts/gen-icons.py
"""
import re
import sys
import urllib.request

BASE = ("https://raw.githubusercontent.com/google/material-design-icons/master"
        "/symbols/web/{n}/materialsymbolsrounded/{n}_24px.svg")

# export name -> Material Symbols name
ICONS = {
    "Add": "add",
    "ArrowForward": "arrow_forward",
    "CalendarMonth": "calendar_month",
    "Check": "check",
    "ChevronRight": "chevron_right",
    "DarkMode": "dark_mode",
    "Delete": "delete",
    "Description": "description",
    "DragIndicator": "drag_indicator",
    "Info": "info",
    "LaptopMac": "laptop_mac",
    "LightMode": "light_mode",
    "PersonAdd": "person_add",
    "ProgressActivity": "progress_activity",
    "Search": "search",
    "Warning": "warning",
}

HEADER = '''import * as React from "react";
import { cn } from "@/lib/cn";

/**
 * Material Symbols (Rounded), vendored as inline SVG.
 *
 * Generated by scripts/gen-icons.py — edit the ICONS map there and re-run
 * rather than hand-editing this file.
 *
 * Vendored rather than pulled from a package because we use ~15 icons and the
 * npm sets ship thousands of files; this keeps install size flat and means no
 * runtime dependency. Material Symbols are Apache-2.0.
 *
 * All paths use the 0 -960 960 960 viewBox Material Symbols standardises on,
 * and fill with currentColor so they inherit text colour. Size comes from a
 * className (`size-4`), which overrides the width/height attributes.
 */

export type IconProps = React.SVGProps<SVGSVGElement>;

function icon(displayName: string, d: string) {
  const Component = React.forwardRef<SVGSVGElement, IconProps>(
    function Icon({ className, ...props }, ref) {
      return (
        <svg
          ref={ref}
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 -960 960 960"
          width="24"
          height="24"
          fill="currentColor"
          aria-hidden="true"
          focusable="false"
          className={cn("shrink-0", className)}
          {...props}
        >
          <path d={d} />
        </svg>
      );
    },
  );
  Component.displayName = displayName;
  return Component;
}
'''


def fetch(name: str) -> str:
    url = BASE.format(n=name)
    with urllib.request.urlopen(url, timeout=30) as r:
        svg = r.read().decode()
    paths = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
    if not paths:
        raise SystemExit(f"no path found in {url}")
    if len(paths) > 1:
        print(f"  ! {name}: {len(paths)} paths, merging", file=sys.stderr)
    return " ".join(paths)


def main():
    out = [HEADER]
    for export, mat in ICONS.items():
        d = fetch(mat)
        print(f"  {export:18} <- {mat} ({len(d)} chars)")
        out.append(f'\nexport const {export} = icon(\n  "{export}",\n  "{d}",\n);')
    target = "src/components/ui/icons.tsx"
    with open(target, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"\nwrote {target} ({len(ICONS)} icons)")


if __name__ == "__main__":
    main()
